personality = "pragmatic"
model = "gpt-5.3-codex"

[mcp_servers.shadcn]
command = "npx"
args = ["shadcn@latest", "mcp"]

[notice.model_migrations]
"gpt-5.2-codex" = "gpt-5.3-codex"

[tui]
notifications = false
